services:
  etl-magic-eden-collection-market:
    container_name: etl-magic-eden-collection-market
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - default
      - influx-network
    env_file:
      - ./.env
    environment:
      INFLUXDB_HOST: http://influxdb:8086
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    ports:
      - 8086:8086
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      INFLUXDB_HOST: http://influxdb:8086
    env_file:
      - ./.env
    networks:
      - default
      - influx-network
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: gradient-gargantuan
    ports:
      - 27017:27017
    volumes:
      - mongodb-storage:/data/db
  mongo-express:
    container_name: mongodb-express
    image: mongo-express
    restart: always
    ports:
      - 8087:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_MONGODB_URL: mongodb://root:rootpassword@mongodb:27017/
networks:
  influx-network:
volumes:
  influxdb-storage:
  mongodb-storage: