{
 "title": "New dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Containers Instances Up (pct)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(up{job=\"prometheus\"})"
    }
   ]
  },
  {
   "title": "State HTTP Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(flask_http_request_total{instance=~\"state:8080\"}[$__rate_interval])"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  { "title": "ETLs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "HTTP POST Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 1, "y": 19 },
   "targets": [
    {
     "expr": "rate(flask_http_request_total{instance=~\"etl-magic-eden-collection-market:8080|etl-magic-eden-collection-xray:8080|etl-magic-eden-global:8080|etl-serum-market:8080|etl-solana-global:8080\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "HTTP POST Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 19 },
   "targets": [
    {
     "expr": "flask_http_request_total{instance=~\"etl-magic-eden-collection-market:8080|etl-magic-eden-collection-xray:8080|etl-magic-eden-global:8080|etl-serum-market:8080|etl-solana-global:8080\"}"
    }
   ]
  }
 ]
}