global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 'localhost:9090'
    - 'api:8080'
    - 'etl-magic-eden-collection-market:8080'
    - 'etl-magic-eden-collection-xray:8080'
    - 'etl-magic-eden-global:8080'
    - 'etl-solana-global:8080'
    - 'etl-serum-market:8080'
    - 'state:8080'